# Site settings
title: Humans of Centre College
description: > # this means to ignore newlines until "baseurl:"
  Humans of Centre College is inspired by the Humans of New York blog. 
  It portrays the lives of Centre students, faculty, and staff.
baseurl: "/humansofcentrecollege" # the subpath of your site, e.g. /blog
url: "https://mhisle22.github.io/" # the base hostname & protocol for your site
keywords: "Humans, Journalism, Centre College, Centre"

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed
  sourcemap: :true

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  # - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-redirect-from
  - jekyll-sitemap

assets:
  digest: false
