# General Links
home: "/"
about: "/about"
request: "/request"
stories: "/stories"
centre: "https://www.centre.edu/"

# Social Media
facebook: "https://www.facebook.com/HumansofCentreCollege/"
instagram: "https://www.instagram.com/centrecollege/"
